config/routes.rb
Rails.application.routes.draw do
  resources :scores, only: [:index, :new, :create]

  resource :leaderboard, only: :show

  devise_for :users

  root to: "leaderboards#show"
end

app/models/rank_manager.rb
class RankManager

  class << self
    def increment_counters(score)
      score.created_by.increment_games_played!
      score.opponent.increment_games_played!
    end

    def honour_points(score)
      winner = score.winner
      loser = score.loser
      points = win_points
      # Bonus points for winning a person with more points
      points += win_bonus_points if loser.points > winner.points
      winner.increment_points!(points)
    end

    def process(score)
      increment_counters(score)
      honour_points(score)
    end

    # Helpers to get points from configuration file, lazy loaded

    def point_values
      @@point_values ||= Rails.application.secrets.points
    end

    def win_points
      point_values['win']
    end

    def lose_points
      point_values['lose']
    end

    def win_bonus_points
      point_values['win_bonus']
    end
  end
end

app/models/score.rb
class Score < ActiveRecord::Base
  belongs_to :created_by, class_name: 'User'
  belongs_to :opponent, class_name: 'User'

  validates :date_played, presence: true
  validates :opponent_id, :created_by_id, presence: true
  validates :score, :opponent_score, numericality: { greater_than: 0, less_than_or_equal_to: 21 }

  validate  :must_not_be_in_the_future
  validate  :must_have_valid_scores

  after_save :rank

  def results(me)
    if created_by == me
      { adversary: opponent, score: score, opponent_score: opponent_score, is_winner: score - opponent_score > 0 }
    else
      { adversary: created_by, score: opponent_score, opponent_score: score, is_winner: opponent_score - score > 0 }
    end
  end

  def winner
    (score - opponent_score) > 0 ? created_by : opponent
  end

  def loser
    ([created_by, opponent] - [winner]).first
  end

  protected

  def must_not_be_in_the_future
    errors.add(:date_played, 'can not be in the future') if date_played && (date_played > Date.today)
  end

  def must_have_valid_scores
    return unless score && opponent_score
    errors.add(:base, 'One of the scores has to be 21') unless (score == 21 && opponent_score != 21) || (score != 21 && opponent_score == 21)
    errors.add(:base, 'There has to be a difference of at least 2 points between scores') if (score - opponent_score).abs < 2
  end

  def rank
    RankManager.process(self)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :trackable, :validatable

  has_many :scores, foreign_key: 'created_by_id'
  has_many :opponent_scores, foreign_key: 'opponent_id', class_name: 'Score'

  scope    :by_desc_points, -> { order(points: :desc) }

  def increment_points!(value)
    self.points += value
    save!
  end

  def increment_games_played!
    self.games_played += 1
    save!
  end

  def opponents
    User.where.not(id: self.id)
  end

  def score_history
    scores + opponent_scores
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/leaderboards_controller.rb
class LeaderboardsController < ApplicationController
  before_action :authenticate_user!

  def show
  end
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  before_action :authenticate_user!

  def index
    @history = current_user.score_history.sort_by { |s| s.date_played }
  end

  def new
    @score = current_user.scores.build
  end

  def create
    @score = current_user.scores.build(score_params)
    if @score.save
      redirect_to action: :index
    else
      render action: :new
    end
  end

  protected

  def score_params
    params.require(:score).permit(:date_played, :opponent_id, :score, :opponent_score)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/views/home/history.html.erb
<h1 class='page-header'>History</h1>

<div class="alert alert-warning" role="alert">This is a sample page. Replace link in the header with your own.</div>

<%= image_tag('history.png') %>

app/views/home/index.html.erb
<h1 class='page-header'>Leaderboard</h1>

<div class="alert alert-warning" role="alert">This is a sample page.</div>

<%= image_tag('leaderboard.png') %>

app/views/home/log.html.erb
<h1 class='page-header'>Log Game</h1>

<div class="alert alert-warning" role="alert">This is a sample page. Replace link in the header with your own.</div>

<%= image_tag('log_game.png') %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Pingpong</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><%= link_to 'Leaderboard', leaderboard_path %></li>
          <li><%= link_to 'Register Score', new_score_path %></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to 'History', scores_path %></li>
          <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Login', new_user_session_path %></li>
          <li><%= link_to 'Sign up', new_user_registration_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pingpong Leaderboard</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css", integrity: "sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==", crossorigin: "anonymous" %>
  <%= javascript_include_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js", integrity: "sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==", crossorigin: "anonymous" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/header' %>

  <div class='container'>
    <%= yield %>
  </div>
</body>
</html>

app/views/leaderboards/show.html.haml
%h1 Leaderboard

%table.table.table-striped
  %thead
    %tr
      %th Rank
      %th Name
      %th Points
      %th Games Played

  - User.by_desc_points.each_with_index do |user, idx|
    %tr
      %td= idx + 1
      %td= user.name
      %td= user.points
      %td= user.games_played

app/views/scores/index.html.haml
%h1 History

%table.table.table-striped
  %thead
    %tr
      %th Date
      %th Opponent
      %th Score
      %th Result

  - @history.each do |score|
    %tr
      %td= score.date_played
      - r = score.results(current_user)
      %td= r[:adversary].name
      %td
        = r[:score]
        \-
        = r[:opponent_score]
      %td= r[:is_winner] ? 'W' : 'L'

app/views/scores/new.html.haml
- if @score.errors.any?
  .row
    .col-lg-12.bg-danger
      - @score.errors.each do |k, err|
        %p
          = k.to_s.humanize unless k == :base
          = err

%h1 New Score

= form_for @score do |f|
  .form-group
    %label Date Played
    = f.date_select :date_played
  .form-group
    %label Opponent
    = f.collection_select :opponent_id, current_user.opponents, :id, :name
  .form-group
    %label Your Score
    = f.number_field :score
  .form-group
    %label Their Score
    = f.number_field :opponent_score
  = f.submit 'Save'